services:
  database:
    container_name: mongodb_dataviewer
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - "27018:27017"
    volumes:
      - mongodb_vol_dataviewer:/data/db

volumes:
  mongodb_vol_dataviewer: 