services:
  database:
    container_name: mongodb_dataviewer
    image: mongo:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "27018:27017"
    volumes:
      - mongodb_vol_dataviewer:/data/db

volumes:
  mongodb_vol_dataviewer: 