name: Continuos Integration

on: [pull_request, push]

jobs: 
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          yarn install

      - name: Build application
        run: |
          cd backend
          yarn build

      - name: Run tests
        run: |
          cd backend
          yarn test